// Code generated by icedrill. DO NOT EDIT.

package domain

import (
	"github.com/pkg/errors"
	"github.com/roblaszczak/icedrill"
)

func NewAccountFromHistory(events []icedrill.Event) (*Account, error) {
	a := &Account{}

	for _, e := range events {
		err := a.update(e)
		if err != nil {
			return nil, err
		}

		a.PopChanges() // todo - test
	}

	return a, nil
}

func (a *Account) recordThat(event icedrill.Event) {
	if event == nil {
		return
	}
	a.es.Changes = append(a.es.Changes, event)
	a.es.Version += 1
}

// todo - test without pitor
// todo - does we need pop?
func (a *Account) PopChanges() []icedrill.Event {
	defer func() { a.es.Changes = nil }()
	return a.es.Changes
}

func (a *Account) update(event icedrill.Event) error {
	switch v := event.(type) {
	case Withdrawed:
		a.handleWithdrawed(v)
	case Deposited:
		a.handleDeposited(v)
	case AccountCreated:
		a.handleAccountCreated(v)
	default:
		return errors.Errorf("event %T is not supported", v)
	}

	a.recordThat(event)

	return nil
}

func (a *Account) Version() uint64 {
	return a.es.Version
}

type AccountRepository interface {
	Save(aggregate *Account) error
	Find(id AccountUUID) (*Account, error)
}
