// Code generated by icedrill. DO NOT EDIT.

package main

import (
	"github.com/pkg/errors"
	"github.com/roblaszczak/icedrill"
)

type Repository struct {
	events map[AccountUUID][]icedrill.Event
}

func NewRepository() *Repository {
	return &Repository{
		events: map[AccountUUID][]icedrill.Event{},
	}
}

func (r *Repository) Save(aggregate *Account) error {
	key := aggregate.UUID()

	if _, ok := r.events[key]; !ok {
		r.events[key] = []icedrill.Event{}
	}

	r.events[key] = append(r.events[key], aggregate.PopChanges()...)

	return nil
}

func (r Repository) Find(id AccountUUID) (*Account, error) {
	events, err := r.findEvents(id)
	if err != nil {
		return nil, err
	}

	return NewAccountFromHistory(events)
}

func (r Repository) findEvents(id AccountUUID) ([]icedrill.Event, error) {
	events, ok := r.events[id]
	if !ok {
		return nil, errors.Errorf("events for aggregate %T %s not found", Account{}, id)
	}

	return events, nil
}
